name: Saludo usando variables
on:
  push
env:
  NIVEL: Senior
jobs:
  mostrar-variables:
    env:
      VARS: ${{ toJSON(vars) }}
    runs-on: ubuntu-latest
    steps:
      - name: imprimir variables
        run: echo $VARS
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
      DESPEDIDA: Cuidate nos vemos pronto
    steps:
      - name: obtener dia de la semana
        run: |
          case "$(date +%u)" in
            1) DIA_DE_SEMANA=Lunes ;;
            2) DIA_DE_SEMANA=Martes ;;
            3) DIA_DE_SEMANA=Miercoles ;;
            4) DIA_DE_SEMANA=Jueves ;;
            5) DIA_DE_SEMANA=Viernes ;;
            6) DIA_DE_SEMANA=Sabado ;;
            7) DIA_DE_SEMANA=Domingo ;;
          esac

          echo "DIA_DE_SEMANA=$DIA_DE_SEMANA" >> "$GITHUB_ENV"
      - name: saludar
        run : echo $SALUDO, $NOMBRE y $NOMBRE2. Eres un verdadero $NIVEL. Hoy es $DIA_DE_SEMANA. $DESPEDIDA
        env:
          NOMBRE2: Curiel
          NOMBRE: ${{ vars.NOMBRE }}
